name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: ./frontend  # Specify the frontend directory
        run: bun install

      - name: Build Svelte app
        working-directory: ./frontend  # Specify the frontend directory
        run: bun build:src

      - name: List Build Output
        working-directory: ./frontend  # Specify the frontend directory
        run: ls -l build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/frontend"  # Point to the frontend directory
          output_location: "frontend/build"  # Output location is the build directory in frontend
