name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: ./frontend
        run: bun install

      - name: Build Svelte app
        working-directory: ./frontend
        run: bun build:src

      - name: List Build Output
        working-directory: ./frontend
        run: ls -l build  # List contents of the build directory to verify output


      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "build"
